import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { 
  Sparkles, ShieldAlert, ArrowLeft, Mail, CheckCircle2, Loader2,
  LayoutDashboard, Users, CreditCard, Landmark, Globe, ToggleLeft,
  Mail as MailIcon, MessageSquare, MessageCircle, Megaphone, 
  ShieldCheck, KeyRound, FileSpreadsheet, Activity, Database
} from 'lucide-react';
import { navigationConfig } from './navConfig';

const iconMap: Record<string, any> = {
  overview: LayoutDashboard,
  users: Users,
  billing: CreditCard,
  licensing: Landmark,
  domains: Globe,
  flags: ToggleLeft,
  mailbox: MailIcon,
  sms: MessageSquare,
  whatsapp: MessageCircle,
  broadcasts: Megaphone,
  access: ShieldCheck,
  sessions: KeyRound,
  health: Activity,
  db: Database
};

const featureDetails: Record<string, { subtitle: string; bulletPoints: string[]; iconColor: string }> = {
  overview: {
    subtitle: "Unified Platform Telemetry & Executive Insights",
    iconColor: "text-blue-500 bg-blue-950/30 border-blue-500/20",
    bulletPoints: [
      "Consolidated multi-tenant platform metrics tracking real-time law firm intake and activity.",
      "Global live-charts showing API usage, query distribution, and platform revenue performance.",
      "Actionable executive notifications on service health and platform growth indexes."
    ]
  },
  users: {
    subtitle: "Cross-Tenant Identity, Authentication & Profile Directory",
    iconColor: "text-indigo-500 bg-indigo-950/30 border-indigo-500/20",
    bulletPoints: [
      "Global user directory allowing search and profile analysis across all tenant companies.",
      "Multi-factor authentication (MFA) enforcement policies and security lockout overrides.",
      "Administrative profile correction, legal license verification, and credential auditing."
    ]
  },
  billing: {
    subtitle: "Global Invoicing, Subscription & Stripe Gateway Administration",
    iconColor: "text-emerald-500 bg-emerald-950/30 border-emerald-500/20",
    bulletPoints: [
      "Manage subscription tiers, custom pricing plans, and individual law firm discount overrides.",
      "Review Stripe webhook status, failed invoice collection queues, and tax configuration.",
      "Generate manual invoices, credit notes, and manage enterprise master contracts."
    ]
  },
  licensing: {
    subtitle: "Enterprise Site Licensing, Seat Quotas & Validation Keys",
    iconColor: "text-cyan-500 bg-cyan-950/30 border-cyan-500/20",
    bulletPoints: [
      "Provision offline-capable enterprise license files and master activation keys.",
      "Manage hard and soft limits for user seat counts per firm and automated overage billing.",
      "Enforce compliance controls regarding paralegal-to-attorney ratio restrictions."
    ]
  },
  domains: {
    subtitle: "Ingress Router, Custom Hostname Verification & SSL/TLS Manager",
    iconColor: "text-sky-500 bg-sky-950/30 border-sky-500/20",
    bulletPoints: [
      "Real-time Let's Encrypt SSL/TLS cert provisioning and auto-renew monitoring.",
      "CNAME/A-record verification system with custom host header edge-routing.",
      "Configure dedicated white-labeled entry portals for enterprise legal networks."
    ]
  },
  flags: {
    subtitle: "Granular Feature Toggles & Canary Release Hypervisor",
    iconColor: "text-amber-500 bg-amber-950/30 border-amber-500/20",
    bulletPoints: [
      "Define and manage global feature flags to activate beta capabilities dynamically.",
      "Execute safe canary rollouts targeting specific geographic legal jurisdictions.",
      "Implement emergency circuit breakers to turn off intensive integrations globally."
    ]
  },
  mailbox: {
    subtitle: "Outbound/Inbound Mail Server Journals & SMTP Queue Diagnostics",
    iconColor: "text-violet-500 bg-violet-950/30 border-violet-500/20",
    bulletPoints: [
      "Real-time diagnostic stream of emails generated by Docket notification queues.",
      "Resolve SMTP relay connection failures, DKIM/SPF alignment, and bounce logs.",
      "Inspect mail payloads in a secure sandbox before outbound dispatch to clients."
    ]
  },
  sms: {
    subtitle: "SMS Gateway Integration, Twilio Trunking & SMS Dispatcher",
    iconColor: "text-orange-500 bg-orange-950/30 border-orange-500/20",
    bulletPoints: [
      "Monitor Twilio and Telnyx SIP trunking status, credit allocations, and API latencies.",
      "Verify carrier delivery logs and inspect automatic appointment reminders dispatch.",
      "Register and manage brand registrations (10DLC / toll-free regulatory compliance)."
    ]
  },
  whatsapp: {
    subtitle: "WhatsApp Business API Sandbox, Consent Manager & Templates",
    iconColor: "text-green-500 bg-green-950/30 border-green-500/20",
    bulletPoints: [
      "Manage Meta Business pre-approved messaging templates and localized translations.",
      "Review user opt-in consent logs and supervise outbound automated client notifications.",
      "Audit conversational queues and message payload delivery metrics."
    ]
  },
  broadcasts: {
    subtitle: "In-App Banners, Platform Maintenance Advisories & System Messages",
    iconColor: "text-rose-500 bg-rose-950/30 border-rose-500/20",
    bulletPoints: [
      "Draft, schedule, and execute system-wide maintenance banners visible to all lawyers.",
      "Target alerts by firm cohort (e.g. notify UK-based tenancies about localized updates).",
      "Manage dismissal settings to guarantee critical updates are acknowledged by firm admins."
    ]
  },
  access: {
    subtitle: "Enterprise RBAC Policies, Security Policies & Elevation Console",
    iconColor: "text-teal-500 bg-teal-950/30 border-teal-500/20",
    bulletPoints: [
      "Modify system roles, granular permission matrices, and security level overrides.",
      "Supervise elevation requests from firm technicians granting temporary support access.",
      "Audit administrative privilege escalation and security key-rotation campaigns."
    ]
  },
  sessions: {
    subtitle: "Live session Explorer, Cookie Journals & Revocation Hub",
    iconColor: "text-fuchsia-500 bg-fuchsia-950/30 border-fuchsia-500/20",
    bulletPoints: [
      "Trace live browser session cookies, device footprints, and geographic IP origins.",
      "Force terminate sessions globally in the event of an active tenant credential breach.",
      "Audit active session durations, average idle times, and concurrency indexes."
    ]
  },
  health: {
    subtitle: "Platform Container Orchestration, CPU/RAM Telemetry & Health Monitor",
    iconColor: "text-red-500 bg-red-950/30 border-red-500/20",
    bulletPoints: [
      "Track Cloud Run container utilization, memory thresholds, and execution lifespans.",
      "Monitor event loop latency, database connection pool sat, and Redis cache hit ratios.",
      "Inspect auto-scaling indicators to anticipate upcoming horizontal load spikes."
    ]
  },
  db: {
    subtitle: "Relational Schema Shell, Safe Diagnostic SQL & Migration Log",
    iconColor: "text-purple-500 bg-purple-950/30 border-purple-500/20",
    bulletPoints: [
      "Execute safe, sandboxed, read-only SQL diagnostics against main relational nodes.",
      "Inspect schema migration state history, database table volumes, and index sizing.",
      "Verify query planner logs to troubleshoot slow indexes in tenant litigation modules."
    ]
  }
};

export const ComingSoonPlaceholder: React.FC = () => {
  const { sectionId } = useParams<{ sectionId: string }>();
  const navigate = useNavigate();
  
  const [email, setEmail] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [success, setSuccess] = useState(false);

  // Find corresponding nav item
  let matchedItem = null;
  for (const group of navigationConfig) {
    const found = group.items.find(i => i.id === sectionId);
    if (found) {
      matchedItem = found;
      break;
    }
  }

  const id = sectionId || 'overview';
  const label = matchedItem ? matchedItem.label : 'Control Module';
  const Icon = iconMap[id] || Sparkles;
  
  const details = featureDetails[id] || {
    subtitle: "SaaS Control Console & Operations Segment",
    iconColor: "text-red-500 bg-red-950/30 border-red-500/20",
    bulletPoints: [
      "SaaS operations controller designed to manage Docket global settings.",
      "Real-time administrative control and policy enforcement rules.",
      "Comprehensive telemetry tracking platform actions and audit events."
    ]
  };

  const handleRegisterBeta = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email.trim()) return;
    setSubmitting(true);
    setTimeout(() => {
      setSubmitting(false);
      setSuccess(true);
      setEmail('');
    }, 1000);
  };

  // @ts-ignore
  const SA_PATH = import.meta.env?.VITE_SUPERADMIN_PATH || 'system-access';

  return (
    <div className="max-w-4xl mx-auto py-8 px-4 font-mono text-zinc-100">
      {/* Back button */}
      <button 
        onClick={() => navigate(`/${SA_PATH}/dashboard`)}
        className="flex items-center gap-2 text-xs text-zinc-500 hover:text-red-400 transition-colors mb-6 group cursor-pointer"
      >
        <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" />
        Return to Core Dashboard
      </button>

      {/* Main Container Card */}
      <div className="bg-[#0c0c12] border border-zinc-900 rounded-xl overflow-hidden shadow-2xl p-8 relative">
        {/* Decorative Grid Lines */}
        <div className="absolute inset-0 bg-[radial-gradient(#1c0909_1px,transparent_1px)] [background-size:16px_16px] opacity-10 pointer-events-none" />

        <div className="relative z-10 space-y-8">
          {/* Header Info */}
          <div className="flex items-start gap-5">
            <div className={`p-4 rounded-xl border ${details.iconColor} shrink-0`}>
              <Icon className="h-8 w-8" />
            </div>
            <div className="space-y-1">
              <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 bg-red-950/40 text-red-400 text-[10px] uppercase font-bold tracking-wider rounded border border-red-900/30">
                <Sparkles className="h-3 w-3" /> Scheduled v2.2 Module
              </div>
              <h2 className="text-xl font-bold text-zinc-200 mt-2">{label}</h2>
              <p className="text-xs text-zinc-400 leading-relaxed font-sans">{details.subtitle}</p>
            </div>
          </div>

          <div className="border-t border-zinc-900 pt-6 space-y-6">
            {/* Functional Specs section */}
            <div>
              <h3 className="text-xs font-bold text-red-500 uppercase tracking-widest mb-3 flex items-center gap-1.5">
                <ShieldAlert className="h-3.5 w-3.5" /> Planned Functional Specifications
              </h3>
              <ul className="space-y-3 pl-1 text-[11px] text-zinc-400 font-mono">
                {details.bulletPoints.map((bp, i) => (
                  <li key={i} className="flex items-start gap-2.5">
                    <span className="text-red-500 select-none mt-0.5">&bull;</span>
                    <span className="leading-relaxed font-sans">{bp}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Simulated Beta Sign-Up Form */}
            <div className="bg-[#09090c] border border-zinc-900 p-6 rounded-lg space-y-4">
              <div className="space-y-1.5">
                <h4 className="text-[11px] font-bold text-zinc-300 uppercase tracking-wider flex items-center gap-1.5">
                  <Mail className="h-3.5 w-3.5 text-red-500" /> Apply for Private Alpha Access
                </h4>
                <p className="text-[10px] text-zinc-500 font-sans leading-relaxed">
                  Join our internal pilot cohort. You will receive notifications directly in your terminal once this core feature is ready for testing.
                </p>
              </div>

              {success ? (
                <div className="p-3.5 bg-emerald-950/20 border border-emerald-900/50 text-emerald-400 text-[11px] rounded-lg flex items-center gap-2.5 animate-in zoom-in-95">
                  <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />
                  <span className="font-sans font-medium">Request logged successfully! Your session key is now queued for this alpha release pipeline.</span>
                </div>
              ) : (
                <form onSubmit={handleRegisterBeta} className="flex gap-2">
                  <input 
                    type="email"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="Enter hypervisor_email@docket.com"
                    className="flex-1 bg-zinc-950 border border-zinc-900 rounded px-3 py-2 text-xs outline-none focus:border-red-950 text-zinc-300 placeholder-zinc-700 font-mono"
                  />
                  <button 
                    type="submit"
                    disabled={submitting}
                    className="p-2 px-4 bg-red-950 hover:bg-red-900 text-red-200 border border-red-500/20 hover:border-red-500/40 font-bold rounded text-xs uppercase cursor-pointer transition-all flex items-center gap-1.5"
                  >
                    {submitting ? (
                      <>
                        <Loader2 className="h-3.5 w-3.5 animate-spin" />
                        LOGGING...
                      </>
                    ) : (
                      "Queue Registration"
                    )}
                  </button>
                </form>
              )}
            </div>
          </div>

          {/* Footer Info inside the card */}
          <div className="pt-2 flex justify-between items-center text-[10px] text-zinc-600 font-mono">
            <span>DOCKET INTEL v2.2-PRE</span>
            <span>HYPERVISOR COHORT SECURE REGIME</span>
          </div>
        </div>
      </div>
    </div>
  );
};
